# This is a basic workflow to help you get started with Actions

name: Build for iOS

# Controls when the action will run. 
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build GL4ES
        run: |
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          mkdir build
          cd build
          cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DDEFAULT_ES=2 -DNOX11=ON -DNOEGL=ON -DSTATICLIB=OFF -DPLATFORM=OS64 -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""
          cmake --build . --config Release --target GL

      - name: Upload lib
        uses: actions/upload-artifact@v2
        with:
          name: libGL
          path: lib/Release
          
